// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "src/Parser.fsy"



# 10 "src/Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | LPAR
  | RPAR
  | LBRA
  | RBRA
  | ASSIGN
  | SEMICOLON
  | IF
  | ELSE
  | WHILE
  | IDENTIFIER of (string)
  | NUM of (int)
  | TRUE
  | FALSE
  | PLUS
  | MINUS
  | EQUAL
  | NOTEQ
  | LESS
  | GREATER
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_LPAR
    | TOKEN_RPAR
    | TOKEN_LBRA
    | TOKEN_RBRA
    | TOKEN_ASSIGN
    | TOKEN_SEMICOLON
    | TOKEN_IF
    | TOKEN_ELSE
    | TOKEN_WHILE
    | TOKEN_IDENTIFIER
    | TOKEN_NUM
    | TOKEN_TRUE
    | TOKEN_FALSE
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_EQUAL
    | TOKEN_NOTEQ
    | TOKEN_LESS
    | TOKEN_GREATER
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startprog
    | NONTERM_exp
    | NONTERM_stmt
    | NONTERM_elseopt
    | NONTERM_prog

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | LPAR  -> 1 
  | RPAR  -> 2 
  | LBRA  -> 3 
  | RBRA  -> 4 
  | ASSIGN  -> 5 
  | SEMICOLON  -> 6 
  | IF  -> 7 
  | ELSE  -> 8 
  | WHILE  -> 9 
  | IDENTIFIER _ -> 10 
  | NUM _ -> 11 
  | TRUE  -> 12 
  | FALSE  -> 13 
  | PLUS  -> 14 
  | MINUS  -> 15 
  | EQUAL  -> 16 
  | NOTEQ  -> 17 
  | LESS  -> 18 
  | GREATER  -> 19 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_LPAR 
  | 2 -> TOKEN_RPAR 
  | 3 -> TOKEN_LBRA 
  | 4 -> TOKEN_RBRA 
  | 5 -> TOKEN_ASSIGN 
  | 6 -> TOKEN_SEMICOLON 
  | 7 -> TOKEN_IF 
  | 8 -> TOKEN_ELSE 
  | 9 -> TOKEN_WHILE 
  | 10 -> TOKEN_IDENTIFIER 
  | 11 -> TOKEN_NUM 
  | 12 -> TOKEN_TRUE 
  | 13 -> TOKEN_FALSE 
  | 14 -> TOKEN_PLUS 
  | 15 -> TOKEN_MINUS 
  | 16 -> TOKEN_EQUAL 
  | 17 -> TOKEN_NOTEQ 
  | 18 -> TOKEN_LESS 
  | 19 -> TOKEN_GREATER 
  | 22 -> TOKEN_end_of_input
  | 20 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startprog 
    | 1 -> NONTERM_exp 
    | 2 -> NONTERM_exp 
    | 3 -> NONTERM_exp 
    | 4 -> NONTERM_exp 
    | 5 -> NONTERM_exp 
    | 6 -> NONTERM_exp 
    | 7 -> NONTERM_exp 
    | 8 -> NONTERM_exp 
    | 9 -> NONTERM_exp 
    | 10 -> NONTERM_exp 
    | 11 -> NONTERM_exp 
    | 12 -> NONTERM_stmt 
    | 13 -> NONTERM_stmt 
    | 14 -> NONTERM_stmt 
    | 15 -> NONTERM_stmt 
    | 16 -> NONTERM_stmt 
    | 17 -> NONTERM_elseopt 
    | 18 -> NONTERM_elseopt 
    | 19 -> NONTERM_prog 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 22 
let _fsyacc_tagOfErrorTerminal = 20

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | LPAR  -> "LPAR" 
  | RPAR  -> "RPAR" 
  | LBRA  -> "LBRA" 
  | RBRA  -> "RBRA" 
  | ASSIGN  -> "ASSIGN" 
  | SEMICOLON  -> "SEMICOLON" 
  | IF  -> "IF" 
  | ELSE  -> "ELSE" 
  | WHILE  -> "WHILE" 
  | IDENTIFIER _ -> "IDENTIFIER" 
  | NUM _ -> "NUM" 
  | TRUE  -> "TRUE" 
  | FALSE  -> "FALSE" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | EQUAL  -> "EQUAL" 
  | NOTEQ  -> "NOTEQ" 
  | LESS  -> "LESS" 
  | GREATER  -> "GREATER" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | LPAR  -> (null : System.Object) 
  | RPAR  -> (null : System.Object) 
  | LBRA  -> (null : System.Object) 
  | RBRA  -> (null : System.Object) 
  | ASSIGN  -> (null : System.Object) 
  | SEMICOLON  -> (null : System.Object) 
  | IF  -> (null : System.Object) 
  | ELSE  -> (null : System.Object) 
  | WHILE  -> (null : System.Object) 
  | IDENTIFIER _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | TRUE  -> (null : System.Object) 
  | FALSE  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | EQUAL  -> (null : System.Object) 
  | NOTEQ  -> (null : System.Object) 
  | LESS  -> (null : System.Object) 
  | GREATER  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us;65535us;10us;65535us;16us;6us;17us;7us;18us;8us;19us;9us;20us;10us;21us;11us;22us;12us;25us;13us;27us;14us;34us;15us;5us;65535us;0us;41us;29us;30us;36us;37us;42us;39us;44us;40us;1us;65535us;31us;32us;1us;65535us;0us;1us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;12us;18us;20us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;1us;1us;1us;2us;1us;3us;1us;4us;7us;5us;5us;6us;7us;8us;9us;10us;7us;5us;6us;6us;7us;8us;9us;10us;7us;5us;6us;7us;7us;8us;9us;10us;7us;5us;6us;7us;8us;8us;9us;10us;7us;5us;6us;7us;8us;9us;9us;10us;7us;5us;6us;7us;8us;9us;10us;10us;7us;5us;6us;7us;8us;9us;10us;11us;7us;5us;6us;7us;8us;9us;10us;13us;7us;5us;6us;7us;8us;9us;10us;14us;7us;5us;6us;7us;8us;9us;10us;15us;1us;5us;1us;6us;1us;7us;1us;8us;1us;9us;1us;10us;1us;11us;1us;11us;1us;13us;1us;13us;1us;14us;1us;14us;1us;14us;1us;14us;2us;14us;16us;1us;14us;1us;14us;1us;15us;1us;15us;1us;15us;1us;15us;2us;15us;16us;1us;15us;2us;16us;16us;2us;16us;18us;2us;16us;19us;1us;16us;1us;18us;1us;18us;1us;18us;1us;19us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;6us;8us;10us;12us;20us;28us;36us;44us;52us;60us;68us;76us;84us;92us;94us;96us;98us;100us;102us;104us;106us;108us;110us;112us;114us;116us;118us;120us;123us;125us;127us;129us;131us;133us;135us;138us;140us;143us;146us;149us;151us;153us;155us;157us;|]
let _fsyacc_action_rows = 47
let _fsyacc_actionTableElements = [|3us;16396us;7us;26us;9us;33us;10us;24us;0us;49152us;0us;16385us;0us;16386us;0us;16387us;0us;16388us;0us;16389us;0us;16390us;2us;16391us;14us;16us;15us;17us;2us;16392us;14us;16us;15us;17us;2us;16393us;14us;16us;15us;17us;2us;16394us;14us;16us;15us;17us;7us;32768us;2us;23us;14us;16us;15us;17us;16us;18us;17us;19us;18us;20us;19us;21us;6us;16397us;14us;16us;15us;17us;16us;18us;17us;19us;18us;20us;19us;21us;7us;32768us;2us;28us;14us;16us;15us;17us;16us;18us;17us;19us;18us;20us;19us;21us;7us;32768us;2us;35us;14us;16us;15us;17us;16us;18us;17us;19us;18us;20us;19us;21us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;0us;16395us;1us;32768us;5us;25us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;1us;32768us;1us;27us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;1us;32768us;3us;29us;3us;16396us;7us;26us;9us;33us;10us;24us;2us;32768us;4us;31us;6us;42us;1us;16401us;8us;43us;0us;16398us;1us;32768us;1us;34us;5us;32768us;1us;22us;10us;5us;11us;2us;12us;3us;13us;4us;1us;32768us;3us;36us;3us;16396us;7us;26us;9us;33us;10us;24us;2us;32768us;4us;38us;6us;42us;0us;16399us;1us;16400us;6us;42us;2us;32768us;4us;45us;6us;42us;2us;32768us;0us;46us;6us;42us;3us;16396us;7us;26us;9us;33us;10us;24us;1us;32768us;3us;44us;3us;16396us;7us;26us;9us;33us;10us;24us;0us;16402us;0us;16403us;|]
let _fsyacc_actionTableRowOffsets = [|0us;4us;5us;6us;7us;8us;9us;10us;11us;14us;17us;20us;23us;31us;38us;46us;54us;60us;66us;72us;78us;84us;90us;96us;97us;99us;105us;107us;113us;115us;119us;122us;124us;125us;127us;133us;135us;139us;142us;143us;145us;148us;151us;155us;157us;161us;162us;|]
let _fsyacc_reductionSymbolCounts = [|1us;1us;1us;1us;1us;3us;3us;3us;3us;3us;3us;3us;0us;3us;8us;7us;3us;0us;4us;2us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;1us;2us;2us;2us;2us;2us;3us;3us;4us;|]
let _fsyacc_immediateActions = [|65535us;49152us;16385us;16386us;16387us;16388us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16395us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16398us;65535us;65535us;65535us;65535us;65535us;16399us;65535us;65535us;65535us;65535us;65535us;65535us;16402us;16403us;|]
let _fsyacc_reductions = lazy [|
# 202 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> AST.Program in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startprog));
# 211 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "src/Parser.fsy"
                                 AST.Num _1 
                   )
# 20 "src/Parser.fsy"
                 : 'gentype_exp));
# 222 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "src/Parser.fsy"
                                  AST.True 
                   )
# 21 "src/Parser.fsy"
                 : 'gentype_exp));
# 232 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 22 "src/Parser.fsy"
                                   AST.False 
                   )
# 22 "src/Parser.fsy"
                 : 'gentype_exp));
# 242 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "src/Parser.fsy"
                                        AST.Var _1 
                   )
# 23 "src/Parser.fsy"
                 : 'gentype_exp));
# 253 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_exp in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "src/Parser.fsy"
                                          AST.Add (_1, _3) 
                   )
# 24 "src/Parser.fsy"
                 : 'gentype_exp));
# 265 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_exp in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "src/Parser.fsy"
                                           AST.Sub (_1, _3) 
                   )
# 25 "src/Parser.fsy"
                 : 'gentype_exp));
# 277 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_exp in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "src/Parser.fsy"
                                           AST.Equal (_1, _3) 
                   )
# 26 "src/Parser.fsy"
                 : 'gentype_exp));
# 289 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_exp in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "src/Parser.fsy"
                                           AST.NotEq (_1, _3) 
                   )
# 27 "src/Parser.fsy"
                 : 'gentype_exp));
# 301 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_exp in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "src/Parser.fsy"
                                          AST.LessThan (_1, _3) 
                   )
# 28 "src/Parser.fsy"
                 : 'gentype_exp));
# 313 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_exp in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "src/Parser.fsy"
                                             AST.GreaterThan (_1, _3) 
                   )
# 29 "src/Parser.fsy"
                 : 'gentype_exp));
# 325 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "src/Parser.fsy"
                                           _2 
                   )
# 30 "src/Parser.fsy"
                 : 'gentype_exp));
# 336 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "src/Parser.fsy"
                             AST.NOP (* Epsilon case *) 
                   )
# 32 "src/Parser.fsy"
                 : 'gentype_stmt));
# 346 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "src/Parser.fsy"
                                                   AST.Assign (_1, _3) 
                   )
# 33 "src/Parser.fsy"
                 : 'gentype_stmt));
# 358 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            let _6 = parseState.GetInput(6) :?> 'gentype_stmt in
            let _8 = parseState.GetInput(8) :?> 'gentype_elseopt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "src/Parser.fsy"
                                                                     AST.If (_3, _6, _8) 
                   )
# 34 "src/Parser.fsy"
                 : 'gentype_stmt));
# 371 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_exp in
            let _6 = parseState.GetInput(6) :?> 'gentype_stmt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "src/Parser.fsy"
                                                                AST.While (_3, _6) 
                   )
# 35 "src/Parser.fsy"
                 : 'gentype_stmt));
# 383 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_stmt in
            let _3 = parseState.GetInput(3) :?> 'gentype_stmt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "src/Parser.fsy"
                                                 AST.Seq (_1, _3) 
                   )
# 36 "src/Parser.fsy"
                 : 'gentype_stmt));
# 395 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "src/Parser.fsy"
                                 AST.NOP (* Epsilon case *) 
                   )
# 38 "src/Parser.fsy"
                 : 'gentype_elseopt));
# 405 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _3 = parseState.GetInput(3) :?> 'gentype_stmt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "src/Parser.fsy"
                                                     _3 
                   )
# 39 "src/Parser.fsy"
                 : 'gentype_elseopt));
# 416 "src/Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_stmt in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "src/Parser.fsy"
                                      _1 
                   )
# 41 "src/Parser.fsy"
                 : AST.Program));
|]
# 428 "src/Parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 23;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let prog lexer lexbuf : AST.Program =
    engine lexer lexbuf 0 :?> _
